# Generated by Django 5.1.1 on 2024-09-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("telephone", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
