# Generated by Django 5.1.1 on 2024-09-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="register",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="telephone",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="register",
            name="firstName",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="register",
            name="lastName",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
