# Generated by Django 5.1.1 on 2024-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=255, null=True)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
    ]
